version: 1
disable_existing_loggers: true
# Configuring the default (root) logger is highly recommended
root:
    level: INFO
    handlers: [console]
loggers:
    tornado.access:
      level: !!python/name:logging.INFO
      handlers: [access]
      qualname: tornado.access
      propagate: false
    werkzeug:
      level: !!python/name:logging.INFO
      handlers: [access]
      qualname: werkzeug
      propagate: false
handlers:
    access:
      class: logging.FileHandler
      filename: access.log
      formatter: simpleFormatter
      level: !!python/name:logging.NOTSET
    console:
      class: logging.StreamHandler
      stream: ext://sys.stderr
      formatter: simpleFormatter
      level: !!python/name:logging.NOTSET
formatters:
    simpleFormatter:
      class: !!python/name:logging.Formatter
      format: "%(asctime)s - %(levelname)s - %(name)s:%(lineno)d  - %(message)s"
      datefmt: "%Y-%m-%dT%H:%M:%S"
